### ISSUE TITLE
Support for Sublime Text 3

### ISSUE THREAD

**Issue by jamonholmgren** [mru2/flog-sublime-plugin#1]
Hey @mru2 ,

I installed this package successfully on ST3 and it shows up in the drop-down:

![screenshot](http://clrsight.co/jh/4zlyix12bh.png)

Nothing happens when I run it, though. Any thoughts?

Thanks!
Jamon

**Comment by mru2** [comment]
Hi @jamonholmgren ! Thanks for the issue ^^

The plugin was not tested with sublime text 3 and used some python 2 - only methods.

I just updated it, and tested it, it seems to work on my machine.

If pulling the last version doesn't solve your problem please reopen this issue. If that's the case there should be a log in the sublime console, could you please also include it? Thanks :)

**Comment by jamonholmgren** [comment]
Sweet, thank you @mru2 ! I'll check it out.

**Comment by jamonholmgren** [comment]
Hm, still having a problem:

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 526, in run_
    return self.run()
  File "/Users/jh/Library/Application Support/Sublime Text 3/Packages/flog-sublime-plugin/Flog.py", line 44, in run
    output =  subprocess.Popen( ("flog " + file_name), stdout=subprocess.PIPE, shell=True).stdout.read()
TypeError: Can't convert 'NoneType' object to str implicitly
```

**Comment by mru2** [comment]
Damn, I knew it was too easy :) I don't know what's causing it, seems to come from the system call to `flog` What's your OS?

Also, could you check in the sublime console : 

```
import subprocess
subprocess.Popen( ("echo 'test'"), stdout=subprocess.PIPE, shell=True).stdout.read()
subprocess.Popen( ("which flog"), stdout=subprocess.PIPE, shell=True).stdout.read()
```

On my machine I've got the following output : 

```
>>> subprocess.Popen( ("echo 'test'"), stdout=subprocess.PIPE, shell=True).stdout.read()
'test\n'
>>> subprocess.Popen( ("which flog"), stdout=subprocess.PIPE, shell=True).stdout.read()
'/usr/bin/flog\n'
```

**Comment by jamonholmgren** [comment]
I'm on OS X 10.9.2.

```
>>> import subprocess
>>> subprocess.Popen( ("echo 'test'"), stdout=subprocess.PIPE, shell=True).stdout.read()
b'test\n'
>>> subprocess.Popen( ("which flog"), stdout=subprocess.PIPE, shell=True).stdout.read()
b''
```

**Comment by mru2** [comment]
Seems like your install of flog is not found. Could you check it's install path in a terminal?

```
rvm use system (is you use rvm)
which flog
rvm use default (is you use rvm)
```

On my machine: 

```
➜  rvm use system
Now using system ruby.
➜  which flog
/usr/bin/flog
➜  rvm use default
Using /Users/david/.rvm/gems/ruby-2.0.0-p451
```

**Comment by jamonholmgren** [comment]
Ah, yes, not using rvm. I use [chruby](https://github.com/postmodern/chruby).

Maybe a nicer error message? I'll install the gem at a system level.
